use-auth.tsx:140 Uncaught Error: useAuth must be used within an AuthProvider
    at useAuth (use-auth.tsx:140:11)
    at NavHeader (nav-header.tsx:40:36)
    at renderWithHooks (chunk-RPCDYKBN.js?v=3212a0aa:11548:26)
    at mountIndeterminateComponent (chunk-RPCDYKBN.js?v=3212a0aa:14926:21)
    at beginWork (chunk-RPCDYKBN.js?v=3212a0aa:15914:22)
    at HTMLUnknownElement.callCallback2 (chunk-RPCDYKBN.js?v=3212a0aa:3674:22)
    at Object.invokeGuardedCallbackDev (chunk-RPCDYKBN.js?v=3212a0aa:3699:24)
    at invokeGuardedCallback (chunk-RPCDYKBN.js?v=3212a0aa:3733:39)
    at beginWork$1 (chunk-RPCDYKBN.js?v=3212a0aa:19765:15)
    at performUnitOfWork (chunk-RPCDYKBN.js?v=3212a0aa:19198:20)
useAuth @ use-auth.tsx:140
NavHeader @ nav-header.tsx:40
renderWithHooks @ chunk-RPCDYKBN.js?v=3212a0aa:11548
mountIndeterminateComponent @ chunk-RPCDYKBN.js?v=3212a0aa:14926
beginWork @ chunk-RPCDYKBN.js?v=3212a0aa:15914
callCallback2 @ chunk-RPCDYKBN.js?v=3212a0aa:3674
invokeGuardedCallbackDev @ chunk-RPCDYKBN.js?v=3212a0aa:3699
invokeGuardedCallback @ chunk-RPCDYKBN.js?v=3212a0aa:3733
beginWork$1 @ chunk-RPCDYKBN.js?v=3212a0aa:19765
performUnitOfWork @ chunk-RPCDYKBN.js?v=3212a0aa:19198
workLoopSync @ chunk-RPCDYKBN.js?v=3212a0aa:19137
renderRootSync @ chunk-RPCDYKBN.js?v=3212a0aa:19116
performConcurrentWorkOnRoot @ chunk-RPCDYKBN.js?v=3212a0aa:18678
workLoop @ chunk-RPCDYKBN.js?v=3212a0aa:197
flushWork @ chunk-RPCDYKBN.js?v=3212a0aa:176
performWorkUntilDeadline @ chunk-RPCDYKBN.js?v=3212a0aa:384Understand this errorAI
use-auth.tsx:140 Uncaught Error: useAuth must be used within an AuthProvider
    at useAuth (use-auth.tsx:140:11)
    at HomePage (home-page.tsx:15:20)
    at renderWithHooks (chunk-RPCDYKBN.js?v=3212a0aa:11548:26)
    at mountIndeterminateComponent (chunk-RPCDYKBN.js?v=3212a0aa:14926:21)
    at beginWork (chunk-RPCDYKBN.js?v=3212a0aa:15914:22)
    at HTMLUnknownElement.callCallback2 (chunk-RPCDYKBN.js?v=3212a0aa:3674:22)
    at Object.invokeGuardedCallbackDev (chunk-RPCDYKBN.js?v=3212a0aa:3699:24)
    at invokeGuardedCallback (chunk-RPCDYKBN.js?v=3212a0aa:3733:39)
    at beginWork$1 (chunk-RPCDYKBN.js?v=3212a0aa:19765:15)
    at performUnitOfWork (chunk-RPCDYKBN.js?v=3212a0aa:19198:20)
useAuth @ use-auth.tsx:140
HomePage @ home-page.tsx:15
renderWithHooks @ chunk-RPCDYKBN.js?v=3212a0aa:11548
mountIndeterminateComponent @ chunk-RPCDYKBN.js?v=3212a0aa:14926
beginWork @ chunk-RPCDYKBN.js?v=3212a0aa:15914
callCallback2 @ chunk-RPCDYKBN.js?v=3212a0aa:3674
invokeGuardedCallbackDev @ chunk-RPCDYKBN.js?v=3212a0aa:3699
invokeGuardedCallback @ chunk-RPCDYKBN.js?v=3212a0aa:3733
beginWork$1 @ chunk-RPCDYKBN.js?v=3212a0aa:19765
performUnitOfWork @ chunk-RPCDYKBN.js?v=3212a0aa:19198
workLoopSync @ chunk-RPCDYKBN.js?v=3212a0aa:19137
renderRootSync @ chunk-RPCDYKBN.js?v=3212a0aa:19116
performConcurrentWorkOnRoot @ chunk-RPCDYKBN.js?v=3212a0aa:18678
workLoop @ chunk-RPCDYKBN.js?v=3212a0aa:197
flushWork @ chunk-RPCDYKBN.js?v=3212a0aa:176
performWorkUntilDeadline @ chunk-RPCDYKBN.js?v=3212a0aa:384Understand this errorAI
use-auth.tsx:140 Uncaught Error: useAuth must be used within an AuthProvider
    at useAuth (use-auth.tsx:140:11)
    at NavHeader (nav-header.tsx:40:36)
    at renderWithHooks (chunk-RPCDYKBN.js?v=3212a0aa:11548:26)
    at mountIndeterminateComponent (chunk-RPCDYKBN.js?v=3212a0aa:14926:21)
    at beginWork (chunk-RPCDYKBN.js?v=3212a0aa:15914:22)
    at HTMLUnknownElement.callCallback2 (chunk-RPCDYKBN.js?v=3212a0aa:3674:22)
    at Object.invokeGuardedCallbackDev (chunk-RPCDYKBN.js?v=3212a0aa:3699:24)
    at invokeGuardedCallback (chunk-RPCDYKBN.js?v=3212a0aa:3733:39)
    at beginWork$1 (chunk-RPCDYKBN.js?v=3212a0aa:19765:15)
    at performUnitOfWork (chunk-RPCDYKBN.js?v=3212a0aa:19198:20)
useAuth @ use-auth.tsx:140
NavHeader @ nav-header.tsx:40
renderWithHooks @ chunk-RPCDYKBN.js?v=3212a0aa:11548
mountIndeterminateComponent @ chunk-RPCDYKBN.js?v=3212a0aa:14926
beginWork @ chunk-RPCDYKBN.js?v=3212a0aa:15914
callCallback2 @ chunk-RPCDYKBN.js?v=3212a0aa:3674
invokeGuardedCallbackDev @ chunk-RPCDYKBN.js?v=3212a0aa:3699
invokeGuardedCallback @ chunk-RPCDYKBN.js?v=3212a0aa:3733
beginWork$1 @ chunk-RPCDYKBN.js?v=3212a0aa:19765
performUnitOfWork @ chunk-RPCDYKBN.js?v=3212a0aa:19198
workLoopSync @ chunk-RPCDYKBN.js?v=3212a0aa:19137
renderRootSync @ chunk-RPCDYKBN.js?v=3212a0aa:19116
recoverFromConcurrentError @ chunk-RPCDYKBN.js?v=3212a0aa:18736
performConcurrentWorkOnRoot @ chunk-RPCDYKBN.js?v=3212a0aa:18684
workLoop @ chunk-RPCDYKBN.js?v=3212a0aa:197
flushWork @ chunk-RPCDYKBN.js?v=3212a0aa:176
performWorkUntilDeadline @ chunk-RPCDYKBN.js?v=3212a0aa:384Understand this errorAI
use-auth.tsx:140 Uncaught Error: useAuth must be used within an AuthProvider
    at useAuth (use-auth.tsx:140:11)
    at HomePage (home-page.tsx:15:20)
    at renderWithHooks (chunk-RPCDYKBN.js?v=3212a0aa:11548:26)
    at mountIndeterminateComponent (chunk-RPCDYKBN.js?v=3212a0aa:14926:21)
    at beginWork (chunk-RPCDYKBN.js?v=3212a0aa:15914:22)
    at HTMLUnknownElement.callCallback2 (chunk-RPCDYKBN.js?v=3212a0aa:3674:22)
    at Object.invokeGuardedCallbackDev (chunk-RPCDYKBN.js?v=3212a0aa:3699:24)
    at invokeGuardedCallback (chunk-RPCDYKBN.js?v=3212a0aa:3733:39)
    at beginWork$1 (chunk-RPCDYKBN.js?v=3212a0aa:19765:15)
    at performUnitOfWork (chunk-RPCDYKBN.js?v=3212a0aa:19198:20)
useAuth @ use-auth.tsx:140
HomePage @ home-page.tsx:15
renderWithHooks @ chunk-RPCDYKBN.js?v=3212a0aa:11548
mountIndeterminateComponent @ chunk-RPCDYKBN.js?v=3212a0aa:14926
beginWork @ chunk-RPCDYKBN.js?v=3212a0aa:15914
callCallback2 @ chunk-RPCDYKBN.js?v=3212a0aa:3674
invokeGuardedCallbackDev @ chunk-RPCDYKBN.js?v=3212a0aa:3699
invokeGuardedCallback @ chunk-RPCDYKBN.js?v=3212a0aa:3733
beginWork$1 @ chunk-RPCDYKBN.js?v=3212a0aa:19765
performUnitOfWork @ chunk-RPCDYKBN.js?v=3212a0aa:19198
workLoopSync @ chunk-RPCDYKBN.js?v=3212a0aa:19137
renderRootSync @ chunk-RPCDYKBN.js?v=3212a0aa:19116
recoverFromConcurrentError @ chunk-RPCDYKBN.js?v=3212a0aa:18736
performConcurrentWorkOnRoot @ chunk-RPCDYKBN.js?v=3212a0aa:18684
workLoop @ chunk-RPCDYKBN.js?v=3212a0aa:197
flushWork @ chunk-RPCDYKBN.js?v=3212a0aa:176
performWorkUntilDeadline @ chunk-RPCDYKBN.js?v=3212a0aa:384Understand this errorAI
chunk-RPCDYKBN.js?v=3212a0aa:14032 The above error occurred in the <NavHeader> component:

    at NavHeader (https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/src/components/nav-header.tsx:73:22)
    at div
    at Router
    at AuthProvider (https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/src/hooks/use-auth.tsx?v=MdTaSZkQg9ionfMl_2sJF:26:32)
    at QueryClientProvider (https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/@tanstack_react-query.js?v=3212a0aa:2805:3)
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ chunk-RPCDYKBN.js?v=3212a0aa:14032
update.callback @ chunk-RPCDYKBN.js?v=3212a0aa:14052
callCallback @ chunk-RPCDYKBN.js?v=3212a0aa:11248
commitUpdateQueue @ chunk-RPCDYKBN.js?v=3212a0aa:11265
commitLayoutEffectOnFiber @ chunk-RPCDYKBN.js?v=3212a0aa:17093
commitLayoutMountEffects_complete @ chunk-RPCDYKBN.js?v=3212a0aa:17980
commitLayoutEffects_begin @ chunk-RPCDYKBN.js?v=3212a0aa:17969
commitLayoutEffects @ chunk-RPCDYKBN.js?v=3212a0aa:17920
commitRootImpl @ chunk-RPCDYKBN.js?v=3212a0aa:19353
commitRoot @ chunk-RPCDYKBN.js?v=3212a0aa:19277
finishConcurrentRender @ chunk-RPCDYKBN.js?v=3212a0aa:18760
performConcurrentWorkOnRoot @ chunk-RPCDYKBN.js?v=3212a0aa:18718
workLoop @ chunk-RPCDYKBN.js?v=3212a0aa:197
flushWork @ chunk-RPCDYKBN.js?v=3212a0aa:176
performWorkUntilDeadline @ chunk-RPCDYKBN.js?v=3212a0aa:384Understand this errorAI
chunk-RPCDYKBN.js?v=3212a0aa:14032 The above error occurred in the <HomePage> component:

    at HomePage (https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/src/pages/home-page.tsx:29:41)
    at Route (https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/wouter.js?v=3212a0aa:323:16)
    at Switch (https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/wouter.js?v=3212a0aa:379:17)
    at div
    at Router
    at AuthProvider (https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/src/hooks/use-auth.tsx?v=MdTaSZkQg9ionfMl_2sJF:26:32)
    at QueryClientProvider (https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/@tanstack_react-query.js?v=3212a0aa:2805:3)
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ chunk-RPCDYKBN.js?v=3212a0aa:14032
update.callback @ chunk-RPCDYKBN.js?v=3212a0aa:14052
callCallback @ chunk-RPCDYKBN.js?v=3212a0aa:11248
commitUpdateQueue @ chunk-RPCDYKBN.js?v=3212a0aa:11265
commitLayoutEffectOnFiber @ chunk-RPCDYKBN.js?v=3212a0aa:17093
commitLayoutMountEffects_complete @ chunk-RPCDYKBN.js?v=3212a0aa:17980
commitLayoutEffects_begin @ chunk-RPCDYKBN.js?v=3212a0aa:17969
commitLayoutEffects @ chunk-RPCDYKBN.js?v=3212a0aa:17920
commitRootImpl @ chunk-RPCDYKBN.js?v=3212a0aa:19353
commitRoot @ chunk-RPCDYKBN.js?v=3212a0aa:19277
finishConcurrentRender @ chunk-RPCDYKBN.js?v=3212a0aa:18760
performConcurrentWorkOnRoot @ chunk-RPCDYKBN.js?v=3212a0aa:18718
workLoop @ chunk-RPCDYKBN.js?v=3212a0aa:197
flushWork @ chunk-RPCDYKBN.js?v=3212a0aa:176
performWorkUntilDeadline @ chunk-RPCDYKBN.js?v=3212a0aa:384Understand this errorAI
chunk-RPCDYKBN.js?v=3212a0aa:19413 Uncaught Error: useAuth must be used within an AuthProvider
    at useAuth (use-auth.tsx:140:11)
    at NavHeader (nav-header.tsx:40:36)
    at renderWithHooks (chunk-RPCDYKBN.js?v=3212a0aa:11548:26)
    at mountIndeterminateComponent (chunk-RPCDYKBN.js?v=3212a0aa:14926:21)
    at beginWork (chunk-RPCDYKBN.js?v=3212a0aa:15914:22)
    at beginWork$1 (chunk-RPCDYKBN.js?v=3212a0aa:19753:22)
    at performUnitOfWork (chunk-RPCDYKBN.js?v=3212a0aa:19198:20)
    at workLoopSync (chunk-RPCDYKBN.js?v=3212a0aa:19137:13)
    at renderRootSync (chunk-RPCDYKBN.js?v=3212a0aa:19116:15)
    at recoverFromConcurrentError (chunk-RPCDYKBN.js?v=3212a0aa:18736:28)
useAuth @ use-auth.tsx:140
NavHeader @ nav-header.tsx:40
renderWithHooks @ chunk-RPCDYKBN.js?v=3212a0aa:11548
mountIndeterminateComponent @ chunk-RPCDYKBN.js?v=3212a0aa:14926
beginWork @ chunk-RPCDYKBN.js?v=3212a0aa:15914
beginWork$1 @ chunk-RPCDYKBN.js?v=3212a0aa:19753
performUnitOfWork @ chunk-RPCDYKBN.js?v=3212a0aa:19198
workLoopSync @ chunk-RPCDYKBN.js?v=3212a0aa:19137
renderRootSync @ chunk-RPCDYKBN.js?v=3212a0aa:19116
recoverFromConcurrentError @ chunk-RPCDYKBN.js?v=3212a0aa:18736
performConcurrentWorkOnRoot @ chunk-RPCDYKBN.js?v=3212a0aa:18684
workLoop @ chunk-RPCDYKBN.js?v=3212a0aa:197
flushWork @ chunk-RPCDYKBN.js?v=3212a0aa:176
performWorkUntilDeadline @ chunk-RPCDYKBN.js?v=3212a0aa:384Understand this errorAI
main.tsx:10 ServiceWorker registration successful: https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/
client:536 WebSocket connection to 'wss://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/?token=mPrBDUCvaDuH' failed: 
setupWebSocket @ client:536
(anonymous) @ client:531Understand this errorAI
 WebSocket connection to 'wss://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/?token=mPrBDUCvaDuH' failed: 
setupWebSocket @ client:536
(anonymous) @ client:531Understand this errorAI
client:536 Uncaught (in promise) SyntaxError: Failed to construct 'WebSocket': The URL 'wss://localhost:undefined/?token=mPrBDUCvaDuH' is invalid.
    at setupWebSocket (client:536:19)
    at fallback (client:509:16)
    at WebSocket.<anonymous> (client:555:7)
setupWebSocket @ client:536
fallback @ client:509
(anonymous) @ client:555Understand this errorAI
injected.js:8 [USO] Button detection aborting due to timeout.
_app-d27e786d61a0d5d7.js:16 Invalid href 'https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev//' passed to next/router in page: '/replEnvironmentDesktop'. Repeated forward-slashes (//) or backslashes \ are not valid in the href.
(anonymous) @ _app-d27e786d61a0d5d7.js:16
d @ main-8a827e96ae76a236.js:1
(anonymous) @ _app-d27e786d61a0d5d7.js:4
useMemo @ framework-e8e972bc54ae0657.js:1
t.useMemo @ framework-e8e972bc54ae0657.js:1
(anonymous) @ _app-d27e786d61a0d5d7.js:4
ld @ framework-e8e972bc54ae0657.js:1
ou @ framework-e8e972bc54ae0657.js:1
i @ framework-e8e972bc54ae0657.js:1
uI @ framework-e8e972bc54ae0657.js:1
(anonymous) @ framework-e8e972bc54ae0657.js:1
uM @ framework-e8e972bc54ae0657.js:1
uS @ framework-e8e972bc54ae0657.js:1
C @ framework-e8e972bc54ae0657.js:1
z @ framework-e8e972bc54ae0657.js:1Understand this errorAI
HikingCompanion:1 Banner not shown: beforeinstallpromptevent.preventDefault() called. The page must call beforeinstallpromptevent.prompt() to show the banner.
framework-e8e972bc54ae0657.js:1 Error while parsing the 'sandbox' attribute: 'allow-downloads-without-user-activation' is an invalid sandbox flag.
_ @ framework-e8e972bc54ae0657.js:1
(anonymous) @ framework-e8e972bc54ae0657.js:1
uD @ framework-e8e972bc54ae0657.js:1
uI @ framework-e8e972bc54ae0657.js:1
(anonymous) @ framework-e8e972bc54ae0657.js:1
uM @ framework-e8e972bc54ae0657.js:1
uS @ framework-e8e972bc54ae0657.js:1
C @ framework-e8e972bc54ae0657.js:1
z @ framework-e8e972bc54ae0657.js:1Understand this errorAI
_app-d27e786d61a0d5d7.js:16 Invalid href 'https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev//' passed to next/router in page: '/replEnvironmentDesktop'. Repeated forward-slashes (//) or backslashes \ are not valid in the href.
(anonymous) @ _app-d27e786d61a0d5d7.js:16
d @ main-8a827e96ae76a236.js:1
(anonymous) @ _app-d27e786d61a0d5d7.js:4
useMemo @ framework-e8e972bc54ae0657.js:1
t.useMemo @ framework-e8e972bc54ae0657.js:1
(anonymous) @ _app-d27e786d61a0d5d7.js:4
ld @ framework-e8e972bc54ae0657.js:1
ou @ framework-e8e972bc54ae0657.js:1
i @ framework-e8e972bc54ae0657.js:1
uI @ framework-e8e972bc54ae0657.js:1
(anonymous) @ framework-e8e972bc54ae0657.js:1
uM @ framework-e8e972bc54ae0657.js:1
uS @ framework-e8e972bc54ae0657.js:1
C @ framework-e8e972bc54ae0657.js:1
z @ framework-e8e972bc54ae0657.js:1Understand this errorAI
workspace_iframe.html:32 Error while parsing the 'sandbox' attribute: 'allow-downloads-without-user-activation' is an invalid sandbox flag.Understand this errorAI
injected.js:8 [USO] Button detection aborting due to timeout.
client:536 WebSocket connection to 'wss://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/?token=mPrBDUCvaDuH' failed: 
setupWebSocket @ client:536
(anonymous) @ client:531Understand this errorAI
use-auth.tsx:140 Uncaught Error: useAuth must be used within an AuthProvider
    at useAuth (use-auth.tsx:140:11)
    at NavHeader (nav-header.tsx:40:36)
    at renderWithHooks (chunk-RPCDYKBN.js?v=3212a0aa:11548:26)
    at mountIndeterminateComponent (chunk-RPCDYKBN.js?v=3212a0aa:14926:21)
    at beginWork (chunk-RPCDYKBN.js?v=3212a0aa:15914:22)
    at HTMLUnknownElement.callCallback2 (chunk-RPCDYKBN.js?v=3212a0aa:3674:22)
    at Object.invokeGuardedCallbackDev (chunk-RPCDYKBN.js?v=3212a0aa:3699:24)
    at invokeGuardedCallback (chunk-RPCDYKBN.js?v=3212a0aa:3733:39)
    at beginWork$1 (chunk-RPCDYKBN.js?v=3212a0aa:19765:15)
    at performUnitOfWork (chunk-RPCDYKBN.js?v=3212a0aa:19198:20)
useAuth @ use-auth.tsx:140
NavHeader @ nav-header.tsx:40
renderWithHooks @ chunk-RPCDYKBN.js?v=3212a0aa:11548
mountIndeterminateComponent @ chunk-RPCDYKBN.js?v=3212a0aa:14926
beginWork @ chunk-RPCDYKBN.js?v=3212a0aa:15914
callCallback2 @ chunk-RPCDYKBN.js?v=3212a0aa:3674
invokeGuardedCallbackDev @ chunk-RPCDYKBN.js?v=3212a0aa:3699
invokeGuardedCallback @ chunk-RPCDYKBN.js?v=3212a0aa:3733
beginWork$1 @ chunk-RPCDYKBN.js?v=3212a0aa:19765
performUnitOfWork @ chunk-RPCDYKBN.js?v=3212a0aa:19198
workLoopSync @ chunk-RPCDYKBN.js?v=3212a0aa:19137
renderRootSync @ chunk-RPCDYKBN.js?v=3212a0aa:19116
performConcurrentWorkOnRoot @ chunk-RPCDYKBN.js?v=3212a0aa:18678
workLoop @ chunk-RPCDYKBN.js?v=3212a0aa:197
flushWork @ chunk-RPCDYKBN.js?v=3212a0aa:176
performWorkUntilDeadline @ chunk-RPCDYKBN.js?v=3212a0aa:384Understand this errorAI
use-auth.tsx:140 Uncaught Error: useAuth must be used within an AuthProvider
    at useAuth (use-auth.tsx:140:11)
    at HomePage (home-page.tsx:15:20)
    at renderWithHooks (chunk-RPCDYKBN.js?v=3212a0aa:11548:26)
    at mountIndeterminateComponent (chunk-RPCDYKBN.js?v=3212a0aa:14926:21)
    at beginWork (chunk-RPCDYKBN.js?v=3212a0aa:15914:22)
    at HTMLUnknownElement.callCallback2 (chunk-RPCDYKBN.js?v=3212a0aa:3674:22)
    at Object.invokeGuardedCallbackDev (chunk-RPCDYKBN.js?v=3212a0aa:3699:24)
    at invokeGuardedCallback (chunk-RPCDYKBN.js?v=3212a0aa:3733:39)
    at beginWork$1 (chunk-RPCDYKBN.js?v=3212a0aa:19765:15)
    at performUnitOfWork (chunk-RPCDYKBN.js?v=3212a0aa:19198:20)
useAuth @ use-auth.tsx:140
HomePage @ home-page.tsx:15
renderWithHooks @ chunk-RPCDYKBN.js?v=3212a0aa:11548
mountIndeterminateComponent @ chunk-RPCDYKBN.js?v=3212a0aa:14926
beginWork @ chunk-RPCDYKBN.js?v=3212a0aa:15914
callCallback2 @ chunk-RPCDYKBN.js?v=3212a0aa:3674
invokeGuardedCallbackDev @ chunk-RPCDYKBN.js?v=3212a0aa:3699
invokeGuardedCallback @ chunk-RPCDYKBN.js?v=3212a0aa:3733
beginWork$1 @ chunk-RPCDYKBN.js?v=3212a0aa:19765
performUnitOfWork @ chunk-RPCDYKBN.js?v=3212a0aa:19198
workLoopSync @ chunk-RPCDYKBN.js?v=3212a0aa:19137
renderRootSync @ chunk-RPCDYKBN.js?v=3212a0aa:19116
performConcurrentWorkOnRoot @ chunk-RPCDYKBN.js?v=3212a0aa:18678
workLoop @ chunk-RPCDYKBN.js?v=3212a0aa:197
flushWork @ chunk-RPCDYKBN.js?v=3212a0aa:176
performWorkUntilDeadline @ chunk-RPCDYKBN.js?v=3212a0aa:384Understand this errorAI
use-auth.tsx:140 Uncaught Error: useAuth must be used within an AuthProvider
    at useAuth (use-auth.tsx:140:11)
    at NavHeader (nav-header.tsx:40:36)
    at renderWithHooks (chunk-RPCDYKBN.js?v=3212a0aa:11548:26)
    at mountIndeterminateComponent (chunk-RPCDYKBN.js?v=3212a0aa:14926:21)
    at beginWork (chunk-RPCDYKBN.js?v=3212a0aa:15914:22)
    at HTMLUnknownElement.callCallback2 (chunk-RPCDYKBN.js?v=3212a0aa:3674:22)
    at Object.invokeGuardedCallbackDev (chunk-RPCDYKBN.js?v=3212a0aa:3699:24)
    at invokeGuardedCallback (chunk-RPCDYKBN.js?v=3212a0aa:3733:39)
    at beginWork$1 (chunk-RPCDYKBN.js?v=3212a0aa:19765:15)
    at performUnitOfWork (chunk-RPCDYKBN.js?v=3212a0aa:19198:20)
useAuth @ use-auth.tsx:140
NavHeader @ nav-header.tsx:40
renderWithHooks @ chunk-RPCDYKBN.js?v=3212a0aa:11548
mountIndeterminateComponent @ chunk-RPCDYKBN.js?v=3212a0aa:14926
beginWork @ chunk-RPCDYKBN.js?v=3212a0aa:15914
callCallback2 @ chunk-RPCDYKBN.js?v=3212a0aa:3674
invokeGuardedCallbackDev @ chunk-RPCDYKBN.js?v=3212a0aa:3699
invokeGuardedCallback @ chunk-RPCDYKBN.js?v=3212a0aa:3733
beginWork$1 @ chunk-RPCDYKBN.js?v=3212a0aa:19765
performUnitOfWork @ chunk-RPCDYKBN.js?v=3212a0aa:19198
workLoopSync @ chunk-RPCDYKBN.js?v=3212a0aa:19137
renderRootSync @ chunk-RPCDYKBN.js?v=3212a0aa:19116
recoverFromConcurrentError @ chunk-RPCDYKBN.js?v=3212a0aa:18736
performConcurrentWorkOnRoot @ chunk-RPCDYKBN.js?v=3212a0aa:18684
workLoop @ chunk-RPCDYKBN.js?v=3212a0aa:197
flushWork @ chunk-RPCDYKBN.js?v=3212a0aa:176
performWorkUntilDeadline @ chunk-RPCDYKBN.js?v=3212a0aa:384Understand this errorAI
use-auth.tsx:140 Uncaught Error: useAuth must be used within an AuthProvider
    at useAuth (use-auth.tsx:140:11)
    at HomePage (home-page.tsx:15:20)
    at renderWithHooks (chunk-RPCDYKBN.js?v=3212a0aa:11548:26)
    at mountIndeterminateComponent (chunk-RPCDYKBN.js?v=3212a0aa:14926:21)
    at beginWork (chunk-RPCDYKBN.js?v=3212a0aa:15914:22)
    at HTMLUnknownElement.callCallback2 (chunk-RPCDYKBN.js?v=3212a0aa:3674:22)
    at Object.invokeGuardedCallbackDev (chunk-RPCDYKBN.js?v=3212a0aa:3699:24)
    at invokeGuardedCallback (chunk-RPCDYKBN.js?v=3212a0aa:3733:39)
    at beginWork$1 (chunk-RPCDYKBN.js?v=3212a0aa:19765:15)
    at performUnitOfWork (chunk-RPCDYKBN.js?v=3212a0aa:19198:20)
useAuth @ use-auth.tsx:140
HomePage @ home-page.tsx:15
renderWithHooks @ chunk-RPCDYKBN.js?v=3212a0aa:11548
mountIndeterminateComponent @ chunk-RPCDYKBN.js?v=3212a0aa:14926
beginWork @ chunk-RPCDYKBN.js?v=3212a0aa:15914
callCallback2 @ chunk-RPCDYKBN.js?v=3212a0aa:3674
invokeGuardedCallbackDev @ chunk-RPCDYKBN.js?v=3212a0aa:3699
invokeGuardedCallback @ chunk-RPCDYKBN.js?v=3212a0aa:3733
beginWork$1 @ chunk-RPCDYKBN.js?v=3212a0aa:19765
performUnitOfWork @ chunk-RPCDYKBN.js?v=3212a0aa:19198
workLoopSync @ chunk-RPCDYKBN.js?v=3212a0aa:19137
renderRootSync @ chunk-RPCDYKBN.js?v=3212a0aa:19116
recoverFromConcurrentError @ chunk-RPCDYKBN.js?v=3212a0aa:18736
performConcurrentWorkOnRoot @ chunk-RPCDYKBN.js?v=3212a0aa:18684
workLoop @ chunk-RPCDYKBN.js?v=3212a0aa:197
flushWork @ chunk-RPCDYKBN.js?v=3212a0aa:176
performWorkUntilDeadline @ chunk-RPCDYKBN.js?v=3212a0aa:384Understand this errorAI
chunk-RPCDYKBN.js?v=3212a0aa:14032 The above error occurred in the <NavHeader> component:

    at NavHeader (https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/src/components/nav-header.tsx:73:22)
    at div
    at Router
    at AuthProvider (https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/src/hooks/use-auth.tsx?v=MdTaSZkQg9ionfMl_2sJF:26:32)
    at QueryClientProvider (https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/@tanstack_react-query.js?v=3212a0aa:2805:3)
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ chunk-RPCDYKBN.js?v=3212a0aa:14032
update.callback @ chunk-RPCDYKBN.js?v=3212a0aa:14052
callCallback @ chunk-RPCDYKBN.js?v=3212a0aa:11248
commitUpdateQueue @ chunk-RPCDYKBN.js?v=3212a0aa:11265
commitLayoutEffectOnFiber @ chunk-RPCDYKBN.js?v=3212a0aa:17093
commitLayoutMountEffects_complete @ chunk-RPCDYKBN.js?v=3212a0aa:17980
commitLayoutEffects_begin @ chunk-RPCDYKBN.js?v=3212a0aa:17969
commitLayoutEffects @ chunk-RPCDYKBN.js?v=3212a0aa:17920
commitRootImpl @ chunk-RPCDYKBN.js?v=3212a0aa:19353
commitRoot @ chunk-RPCDYKBN.js?v=3212a0aa:19277
finishConcurrentRender @ chunk-RPCDYKBN.js?v=3212a0aa:18760
performConcurrentWorkOnRoot @ chunk-RPCDYKBN.js?v=3212a0aa:18718
workLoop @ chunk-RPCDYKBN.js?v=3212a0aa:197
flushWork @ chunk-RPCDYKBN.js?v=3212a0aa:176
performWorkUntilDeadline @ chunk-RPCDYKBN.js?v=3212a0aa:384Understand this errorAI
chunk-RPCDYKBN.js?v=3212a0aa:14032 The above error occurred in the <HomePage> component:

    at HomePage (https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/src/pages/home-page.tsx:29:41)
    at Route (https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/wouter.js?v=3212a0aa:323:16)
    at Switch (https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/wouter.js?v=3212a0aa:379:17)
    at div
    at Router
    at AuthProvider (https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/src/hooks/use-auth.tsx?v=MdTaSZkQg9ionfMl_2sJF:26:32)
    at QueryClientProvider (https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/@tanstack_react-query.js?v=3212a0aa:2805:3)
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ chunk-RPCDYKBN.js?v=3212a0aa:14032
update.callback @ chunk-RPCDYKBN.js?v=3212a0aa:14052
callCallback @ chunk-RPCDYKBN.js?v=3212a0aa:11248
commitUpdateQueue @ chunk-RPCDYKBN.js?v=3212a0aa:11265
commitLayoutEffectOnFiber @ chunk-RPCDYKBN.js?v=3212a0aa:17093
commitLayoutMountEffects_complete @ chunk-RPCDYKBN.js?v=3212a0aa:17980
commitLayoutEffects_begin @ chunk-RPCDYKBN.js?v=3212a0aa:17969
commitLayoutEffects @ chunk-RPCDYKBN.js?v=3212a0aa:17920
commitRootImpl @ chunk-RPCDYKBN.js?v=3212a0aa:19353
commitRoot @ chunk-RPCDYKBN.js?v=3212a0aa:19277
finishConcurrentRender @ chunk-RPCDYKBN.js?v=3212a0aa:18760
performConcurrentWorkOnRoot @ chunk-RPCDYKBN.js?v=3212a0aa:18718
workLoop @ chunk-RPCDYKBN.js?v=3212a0aa:197
flushWork @ chunk-RPCDYKBN.js?v=3212a0aa:176
performWorkUntilDeadline @ chunk-RPCDYKBN.js?v=3212a0aa:384Understand this errorAI
chunk-RPCDYKBN.js?v=3212a0aa:19413 Uncaught Error: useAuth must be used within an AuthProvider
    at useAuth (use-auth.tsx:140:11)
    at NavHeader (nav-header.tsx:40:36)
    at renderWithHooks (chunk-RPCDYKBN.js?v=3212a0aa:11548:26)
    at mountIndeterminateComponent (chunk-RPCDYKBN.js?v=3212a0aa:14926:21)
    at beginWork (chunk-RPCDYKBN.js?v=3212a0aa:15914:22)
    at beginWork$1 (chunk-RPCDYKBN.js?v=3212a0aa:19753:22)
    at performUnitOfWork (chunk-RPCDYKBN.js?v=3212a0aa:19198:20)
    at workLoopSync (chunk-RPCDYKBN.js?v=3212a0aa:19137:13)
    at renderRootSync (chunk-RPCDYKBN.js?v=3212a0aa:19116:15)
    at recoverFromConcurrentError (chunk-RPCDYKBN.js?v=3212a0aa:18736:28)
useAuth @ use-auth.tsx:140
NavHeader @ nav-header.tsx:40
renderWithHooks @ chunk-RPCDYKBN.js?v=3212a0aa:11548
mountIndeterminateComponent @ chunk-RPCDYKBN.js?v=3212a0aa:14926
beginWork @ chunk-RPCDYKBN.js?v=3212a0aa:15914
beginWork$1 @ chunk-RPCDYKBN.js?v=3212a0aa:19753
performUnitOfWork @ chunk-RPCDYKBN.js?v=3212a0aa:19198
workLoopSync @ chunk-RPCDYKBN.js?v=3212a0aa:19137
renderRootSync @ chunk-RPCDYKBN.js?v=3212a0aa:19116
recoverFromConcurrentError @ chunk-RPCDYKBN.js?v=3212a0aa:18736
performConcurrentWorkOnRoot @ chunk-RPCDYKBN.js?v=3212a0aa:18684
workLoop @ chunk-RPCDYKBN.js?v=3212a0aa:197
flushWork @ chunk-RPCDYKBN.js?v=3212a0aa:176
performWorkUntilDeadline @ chunk-RPCDYKBN.js?v=3212a0aa:384Understand this errorAI
client:536 Uncaught (in promise) SyntaxError: Failed to construct 'WebSocket': The URL 'wss://localhost:undefined/?token=mPrBDUCvaDuH' is invalid.
    at setupWebSocket (client:536:19)
    at fallback (client:509:16)
    at WebSocket.<anonymous> (client:555:7)
setupWebSocket @ client:536
fallback @ client:509
(anonymous) @ client:555Understand this errorAI
main.tsx:10 ServiceWorker registration successful: https://f01fa5b6-54a1-4a7d-a31b-baa3e96c396e-00-2bjxrn3mcs2ab.janeway.replit.dev/